### ISSUE TITLE
Issue in Query - read([ abc])

### ISSUE THREAD

**Issue by ashish9308** [IBM-Blockchain/chaincode-investigator#1]
When sending value abc to Query - read([ abc]) , Getting an error like :
Error - read {
    "readyState": 0,
    "responseText": "",
    "status": 0,
    "statusText": "error"
}

Please send me the resolution.

**Comment by dshuffma-ibm** [comment]
so few questions:

- are you using a network via the Bluemix service? or one you stood up yourself
- have you deployed chaincode?
- what chaincode was deployed?

**Comment by ashish9308** [comment]
Yes I'm using a network via Bluemix services and I have followed the same approach which is mentioned there in your readme file of chaincode investigator.
1. Created one blockchain service using bluemix.
2. Using this json in load section 

{
    "network": {
        "peers": [
            {
                "api_host": "ed4b8fa3-0ec7-4aa5-92af-8b3c2b933c33_vp0.us.blockchain.ibm.com",
                "api_port": 443,
                "api_port_tls": 443,
                "id": "ed4b8fa3-0ec7-4aa5-92af-8b3c2b933c33_vp0"
            }
        ],
        "users": [
            {
                "username": "user_type1_b4bba34181",
                "secret": "a8a56e7795",
                "enrollId": "user_type1_b4bba34181",
                "enrollSecret": "a8a56e7795"
            }
        ]
    },
    "chaincode": {
        "zip_url": "https://github.com/ibm-blockchain/marbles-chaincode/archive/master.zip",
        "unzip_dir": "marbles-chaincode-master/hyperledger/part2",
        "git_url": "https://github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2"
    }
}

3. Then clicked on Send to SDK Button 
4. Now I'm able to see chaincode summery icon.
5. But when trying to query the current cc state for the value of abc

Getting the error -
Error - read {
"readyState": 0,
"responseText": "",
"status": 0,
"statusText": "error"
}

One more Issue I noticed that the chaincode Id which is generated in Bluemix service after clicking on send to Sdk button is removed automatically after 10-15 minutes.
Please help me on this.

**Comment by dshuffma-ibm** [comment]
Looks like I goofed and had it hard coded to use `http` which no longer works on bluemix networks.  I have pushed new changes that should allow detect `http` or `https` from the input settings.  Also in the network panel I added a port and a tls field to manually set them.

Please pull the changes and try again!

(I haven't tested all of cci yet, I'll try to do that tomorrow)

**Comment by ashish9308** [comment]
Thanks dshuffma for your quick help. The issue is now resolved and I'm able to deploy the cc from this chaincode testing UI .
